/**
 * `/docs` — the public API reference, wearing the site's chrome.
 *
 * The reference itself is generated by `HttpApiScalar` inside the **backend**
 * Worker and served at `/v1/docs` through the `/v1/$` proxy. That page is a
 * complete standalone document with its own <html>, so it cannot be rendered
 * inside this route's tree — which is why visiting `/v1/docs` directly drops
 * the header and leaves no way back.
 *
 * Framing it keeps one source of truth for the spec (the API describes itself;
 * nothing here restates it) while giving the page a header, a footer and a
 * route that belongs to the site. The alternative — mounting Scalar a second
 * time in this Worker — would mean shipping its ~3&nbsp;MB bundle twice and
 * keeping two copies of the configuration in step.
 *
 * `/v1/docs` remains reachable on its own for anyone who wants the bare page.
 */
import { createFileRoute } from "@tanstack/react-router";
import * as stylex from "@stylexjs/stylex";

import { Container, MarketingLayout } from "~/client/chrome";
import { Heading, Row, Stack, Text } from "~/components";
import { color, font, radius, space } from "~/styles/tokens.stylex";

export const Route = createFileRoute("/(marketing)/docs")({
  head: () => ({
    meta: [
      { title: "API reference — Kindling" },
      {
        name: "description",
        content:
          "The Kindling v1 REST API: projects endpoints, API key authentication, and an OpenAPI 3.1 specification you can generate clients from.",
      },
    ],
  }),
  component: DocsPage,
});

const styles = stylex.create({
  intro: {
    paddingBlockEnd: space.lg,
    paddingBlockStart: space.xxl,
  },
  // The frame is sized to the viewport minus the header, so the reference gets
  // its own scroll context and the site header stays put above it.
  frameWrap: {
    borderColor: color.border,
    borderRadius: radius.lg,
    borderStyle: "solid",
    borderWidth: 1,
    overflow: "hidden",
    backgroundColor: color.surface,
    marginBlockEnd: space.xxl,
  },
  frame: {
    borderStyle: "none",
    borderWidth: 0,
    display: "block",
    height: "calc(100vh - 190px)",
    minHeight: 520,
    width: "100%",
  },
  meta: {
    fontFamily: font.mono,
    fontSize: font.sizeXs,
  },
  link: {
    color: { default: color.primaryText, ":hover": color.text },
  },
});

function DocsPage() {
  return (
    <MarketingLayout>
      <Container>
        <Stack gap="sm" style={styles.intro}>
          <Heading level={2} as="h1">
            API reference
          </Heading>
          <Text tone="muted">
            The <code>/v1</code> REST API, generated from the same contract the server implements —
            so it cannot drift from the code. Authenticate with an API key from{" "}
            <a href="/app/settings/api-keys" {...stylex.props(styles.link)}>
              your settings
            </a>
            .
          </Text>
          <Row gap="md" wrap style={styles.meta}>
            <Text mono size="xs" tone="subtle">
              <a href="/v1/openapi.json" {...stylex.props(styles.link)}>
                openapi.json
              </a>
            </Text>
            <Text mono size="xs" tone="subtle">
              <a href="/v1/docs" {...stylex.props(styles.link)}>
                full-page reference
              </a>
            </Text>
          </Row>
        </Stack>
      </Container>
      <Container>
        <div {...stylex.props(styles.frameWrap)}>
          <iframe
            src="/v1/docs"
            title="Kindling v1 API reference"
            {...stylex.props(styles.frame)}
          />
        </div>
      </Container>
    </MarketingLayout>
  );
}
