/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as RpcRouteImport } from './routes/rpc'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as marketingIndexRouteImport } from './routes/(marketing)/index'
import { Route as marketingPricingRouteImport } from './routes/(marketing)/pricing'
import { Route as AppAppDashboardRouteImport } from './routes/_app/app/dashboard'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as AppAppSettingsProfileRouteImport } from './routes/_app/app/settings/profile'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcRoute = RpcRouteImport.update({
  id: '/rpc',
  path: '/rpc',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingIndexRoute = marketingIndexRouteImport.update({
  id: '/(marketing)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingPricingRoute = marketingPricingRouteImport.update({
  id: '/(marketing)/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppDashboardRoute = AppAppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppSettingsProfileRoute = AppAppSettingsProfileRouteImport.update({
  id: '/app/settings/profile',
  path: '/app/settings/profile',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof marketingIndexRoute
  '/rpc': typeof RpcRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/pricing': typeof marketingPricingRoute
  '/app/dashboard': typeof AppAppDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/settings/profile': typeof AppAppSettingsProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof marketingIndexRoute
  '/rpc': typeof RpcRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/pricing': typeof marketingPricingRoute
  '/app/dashboard': typeof AppAppDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/settings/profile': typeof AppAppSettingsProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/rpc': typeof RpcRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(marketing)/pricing': typeof marketingPricingRoute
  '/(marketing)/': typeof marketingIndexRoute
  '/_app/app/dashboard': typeof AppAppDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/app/settings/profile': typeof AppAppSettingsProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rpc'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/pricing'
    | '/app/dashboard'
    | '/api/auth/$'
    | '/app/settings/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rpc'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/pricing'
    | '/app/dashboard'
    | '/api/auth/$'
    | '/app/settings/profile'
  id:
    | '__root__'
    | '/_app'
    | '/rpc'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/reset-password'
    | '/(marketing)/pricing'
    | '/(marketing)/'
    | '/_app/app/dashboard'
    | '/api/auth/$'
    | '/_app/app/settings/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  RpcRoute: typeof RpcRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  marketingPricingRoute: typeof marketingPricingRoute
  marketingIndexRoute: typeof marketingIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc': {
      id: '/rpc'
      path: '/rpc'
      fullPath: '/rpc'
      preLoaderRoute: typeof RpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/': {
      id: '/(marketing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof marketingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/pricing': {
      id: '/(marketing)/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof marketingPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app/dashboard': {
      id: '/_app/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppAppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app/settings/profile': {
      id: '/_app/app/settings/profile'
      path: '/app/settings/profile'
      fullPath: '/app/settings/profile'
      preLoaderRoute: typeof AppAppSettingsProfileRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAppDashboardRoute: typeof AppAppDashboardRoute
  AppAppSettingsProfileRoute: typeof AppAppSettingsProfileRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppDashboardRoute: AppAppDashboardRoute,
  AppAppSettingsProfileRoute: AppAppSettingsProfileRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  RpcRoute: RpcRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  marketingPricingRoute: marketingPricingRoute,
  marketingIndexRoute: marketingIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
